### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by duyuxuan** [fastapi-admin/fastapi-admin#48]
docker image fastapi-admin cannot start. no error log.

**Comment by long2ice** [comment]
build it with `Dockerfile`

**Comment by duyuxuan** [comment]
@long2ice 

i build a docker compose file like this:
```
version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fastapi-admin
      TZ: 'Asia/Shanghai'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 3306:3306
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_PASSWORD: 654321
      REDIS_DB: 0
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes
  api:
    build: .
    environment:
      DATABASE_URL: mysql://root:123456@mysql:3306/fastapi-admin
    ports:
      - '8000:8000'
    depends_on:
      - mysql
    image: fastapi-admin
    command: uvicorn examples.main:app_ --port 8000 --host 0.0.0.0
```

**Comment by long2ice** [comment]
see https://github.com/fastapi-admin/fastapi-admin#run-examples-in-local, you need add redis env items in your api

**Comment by duyuxuan** [comment]
@long2ice 
Thanks a lot.
I know there must be have a local Redis environment.
I just want to deploy all environment with one docker-compose.yml.
Now I can do it.

```
version: '3.7'
services:
  api:
    build: .
    environment:
      DATABASE_URL: mysql://root:123456@db:3306/fastapi-admin
    image: fastapi-admin
    command: uvicorn examples.main:app_ --port 8000 --host 0.0.0.0
    ports:
      - 80:8000
    networks:
      - redisnet
      - dbnet
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=mysql://root:123456@db:3306/fastapi-admin
  redis:
    image: redis:alpine
    networks:
      - redisnet
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=654321
      - REDIS_DB=0
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes
    expose:
      - 6379
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dbnet
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=fastapi-admin
      - TZ='Asia/Shanghai'
    expose:
      - 3306
volumes:
  db_data:
networks:
  dbnet:
  redisnet:
```
